spring:
  application:
    name: "realestate"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: create-drop
